### ISSUE TITLE
forkpty() failed

### ISSUE THREAD

**Issue by Jan200101** [meefik/wshell#1]
Error : 

> forkpty() failed
> Session closed.

**Comment by sruafly425** [comment]
Same issue here. I'm looking for solution

**Comment by Jan200101** [comment]
@sruafly425 I suggest using [shellinabox](https://github.com/shellinabox/shellinabox) which is a bit more up to date and works last time I tried

**Comment by sruafly425** [comment]
Do you mean you used original [shellinabox](https://github.com/shellinabox/shellinabox) instead?

**Comment by Jan200101** [comment]
I'm saying that wshell has been unmaintained and unsupported for many years now and that you should use shellinabox or other solutions instead

**Comment by sruafly425** [comment]
the solution is user=0
``
./shellinaboxd -t -p --user=0
 ``
but this method requires root...

**Comment by sruafly425** [comment]
I installed linux on my phone, install shellinabox, connected via ADB.
What method did you use?
